routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::group(['namespace'=>'Frontend'],function(){

//     Route::get('/', [   'uses' => 'HomeController@index'])->name('index');
//     Route::get('/media', ['uses' => 'HomeController@media'])->name('media');
//     Route::get('/contact', ['uses' => 'HomeController@contact'])->name('contact');
//     Route::get('/faq', ['uses' => 'HomeController@faq'])->name('faq');
//     Route::get('/gallery', ['uses' => 'HomeController@gallery'])->name('gallery');
//     Route::get('/awards', ['uses' => 'HomeController@awards'])->name('awards');
//     Route::get('/case-studies', ['uses' => 'HomeController@caseStudies'])->name('casestudies');
//     Route::get('/case-study/{slug}', ['uses' => 'HomeController@caseStudydetails'])->name('casestudy.details');
// });

Route::get('/manage', ['uses' => 'Admin\AdminController@login'])->name('admin.login.form');
Route::post('login', ['uses' => 'Admin\AdminController@adminLogin'])->name('admin.login');

Route::group(['prefix' => 'admin-manage', 'namespace' => 'Admin','as'=>'admin.', 'middleware' => 'isAdmin'], function () {

    Route::post('logout', ['uses' => 'AdminController@logout'])->name('logout');
    Route::get('dashboard', ['uses' => 'AdminController@dashboard'])->name('dashboard');

    Route::get('user-list', ['uses' => 'UserController@index'])->name('users');
    Route::get('user-create', ['uses' => 'UserController@create'])->name('user.create');
    Route::post('store-user', ['uses' => 'UserController@store'])->name('user.save');
    Route::get('edit-user/{id}', ['uses' => 'UserController@edit'])->name('user.edit');
    Route::post('update-user', ['uses' => 'UserController@update'])->name('user.update');
    Route::post('delete-user', ['uses' => 'UserController@delete'])->name('user.delete');

    Route::get('group-list', ['uses' => 'GroupController@index'])->name('groups');
    Route::get('group-create', ['uses' => 'GroupController@create'])->name('group.create');
    Route::post('store-groups', ['uses' => 'GroupController@store'])->name('group.save');
    Route::get('edit-groups/{id}', ['uses' => 'GroupController@edit'])->name('group.edit');
    Route::post('update-groups', ['uses' => 'GroupController@update'])->name('group.update');
    Route::post('delete-groups', ['uses' => 'GroupController@delete'])->name('group.delete');

    Route::get('add-user-to-groups/{id}', ['uses' => 'GroupController@addUsers'])->name('group.add.user');
    Route::post('add-user-to-group', ['uses' => 'GroupController@addUsersToGroup'])->name('group.add-user');
    Route::get('create-expense/{id}', ['uses' => 'GroupController@createExpense'])->name('group.expense.create');
    Route::post('store-expense', ['uses' => 'GroupController@storeExpense'])->name('store.expense');
    Route::get('view-expense/{id}', ['uses' => 'GroupController@viewExpense'])->name('group.expense.view');
    Route::get('view-bill/{id}', ['uses' => 'GroupController@viewExpenseDetails'])->name('expense.detail');


});

app/Models/Group.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    use HasFactory;
    protected $fillable = ['title', 'description'];

    public function users()
    {
        return $this->belongsToMany('App\Models\User');
    }
}

app/Http/Controllers/Admin/GroupController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Expense;
use App\Models\Group;
use App\Models\User;
use App\Models\UserExpense;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

class GroupController extends Controller
{
    /**
     * Show the groups for a given user.
     * @return \Illuminate\View\View
     */
    public function index()
    {

        $groups = Group::latest()->get();
        return view('admin.groups.index', compact('groups'));
    }
    /**
     * Create the given group.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.groups.create');
    }
    /**
     * Edit the given group.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  string  $id
     * @return \Illuminate\View\View
     */
    public function edit($id)
    {
        $group = Group::find(decrypt($id));
        return view('admin.groups.edit', compact('group'));
    }
    /**
     * Store the group.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $validator = Validator::make(request()->all(), [
            'title' => 'required', 'description' => 'required'
        ], ['name.required' => 'Please Fill Title']);
        if ($validator->passes()) {
            $input = request()->except('_token');
            Group::create($input);
            return back()->with('message', 'Successfully Created New Group');
        } else {
            return back()->withErrors($validator)->withInput(request()->all());
        }
    }
    /**
     * Update the group.
     * @param  string  $id
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {

        $id = decrypt($request->group_id);
        $validator = Validator::make(request()->all(), [
            'title' => 'required', 'description' => 'required'
        ], ['name.required' => 'Please Fill Title']);
        if ($validator->passes()) {
            $input = request()->except('_token');
            Group::find($id)->update($input);
            return back()->with('message', 'Successfully Updated Group');
        } else {

            return back()->withErrors($validator)->withInput(request()->all());
        }
    }
    /**
     * add users to  the group.
     * @param  string  $id
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\View\View
     */
    public function addUsers($group_id)
    {
        $group_id = decrypt($group_id);
        $users = User::latest()->get();
        $user = new User();

        return view('admin.groups.add_user_to_group', compact('group_id', 'users'));
    }
    /**
     * Add users to  the group.
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function addUsersToGroup(Request $request)
    {
        $users = $request->users;
        $group = Group::find($request->group_id);
        $group->users()->sync($users);
        return back()->with('message', 'Successfully Updated Group');
    }
    /**
     * create Expense
     * @param  \Illuminate\Http\Request  $request
     * @param  string  $id
     * @return \Illuminate\View\View
     */
    public function createExpense($group_id)
    {
        $users = User::latest()->get();
        $group_id = decrypt($group_id);
        return view('admin.groups.create_expense', compact('group_id', 'users'));
    }
    /**
     * Store Expense
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function storeExpense(Request $request)
    {
        $users = $request->users;
        $group = Group::find($request->group_id);
        $totalAmount = $request->total_amount;
        /* creating expense */
        $expense = Expense::create([
            'title' => $request->title, 'description' => $request->description,
            'total_amount' => $totalAmount,'group_id'=> $group->id, 'user_id' => 1
        ]); // 1 for admin

        if ($expense) {
            $numberOfUsers = count($users);
            $splitAmount = ((float) $totalAmount  / (float) $numberOfUsers);
            foreach ($users as $user) {
                UserExpense::create(['expense_id' => $expense->id, 'amount' => $splitAmount, 'user_id' => $user]); // updating split amount to each users
            }
        }
        return back()->with('message', 'Successfully Updated Expense Details');
    }
    public function viewExpense($group_id)
    {
        $users = User::latest()->get();
        $group_id = decrypt($group_id);
        $group = Group::find($group_id);
        $expenses = Expense::where('group_id',$group_id)->get();
        return view('admin.groups.view_expense', compact('group', 'users','expenses'));

    }
    public function delete(Request $request)
    {
        $id = $request->id;
        $data = Group::find(decrypt($id));
        $data->delete();
        return redirect(route('admin.groups'))->with('success', 'Successfully Deleted Group');
    }

    public function viewExpenseDetails($id)
    {
        $expenseId = decrypt($id);
        $expenses = UserExpense::with('user')->where('expense_id',$expenseId)->get();
        // return $expenses;
        return view('admin.groups.view_expense_detail', compact('expenses'));

    }
}

resources/views/admin/groups/add_user_to_group.blade.php
@extends('admin.layouts.master')

@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Group
      <small>Manage</small>
    </h1>

    @if ($message = Session::get('message'))
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <h5><i class="icon fa fa-check"></i> {!! $message !!}</h5>

    </div>
    @endif
  </section>

  <section class="content">
    <div class="container-fluid">
      <div class="row">

        <div class="col-md-12">
          <div class="card card-primary">
            <div class="card-header">

              <h3 class="card-title">Add User to Group</h3>
            </div>

            <form action="{{route('admin.group.add-user')}}" method="POST" enctype="multipart/form-data">
              @csrf
              <input type="hidden" name="group_id" value="{{$group_id}}">
              <div class="card-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">Users</label>
                  <select class="selectpicker" name="users[]" multiple data-live-search="true">
                    @foreach($users as $user)
                    <option value="{{$user->id}}">{{$user->name}}</option>
                    @endforeach
                  </select>
                </div>
              </div>
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
        </div>

      </div>


  </section>
</div>
<script>
  $('select').selectpicker();

</script>
@endsection

resources/views/admin/groups/create.blade.php
@extends('admin.layouts.master')

@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Group
      <small>Manage</small>
    </h1>

    @if ($message = Session::get('message'))
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <h5><i class="icon fa fa-check"></i> {!! $message !!}</h5>

    </div>
    @endif
  </section>

  <section class="content">
    <div class="container-fluid">
      <div class="row">

        <div class="col-md-12">
          <div class="card card-primary">
            <div class="card-header">

              <h3 class="card-title">Create Group</h3>
            </div>

            <form action="{{route('admin.group.save')}}" method="POST" enctype="multipart/form-data">
              @csrf
              <div class="card-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">Title</label>
                  <input type="tezt" name="title" class="form-control" id="title" value="{{ old('title') }}" placeholder="Enter Title">
                  {!! $errors->first('title', '<p style="color:red;" class="help-block error">:message</p>') !!}
                </div>
                <div class="form-group">
                  <label for="exampleInputEmail1">Description</label>
                  <input type="tezt" name="description" class="form-control" id="description" value="{{ old('description') }}" placeholder="Enter Desc">
                  {!! $errors->first('description', '<p style="color:red;" class="help-block error">:message</p>') !!}
                </div>
              </div>
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
        </div>

      </div>


  </section>
</div>

@endsection

resources/views/admin/groups/create_expense.blade.php
@extends('admin.layouts.master')

@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Expense
      <small>Manage</small>
    </h1>

    @if ($message = Session::get('message'))
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <h5><i class="icon fa fa-check"></i> {!! $message !!}</h5>

    </div>
    @endif
  </section>

  <section class="content">
    <div class="container-fluid">
      <div class="row">

        <div class="col-md-12">
          <div class="card card-primary">
            <div class="card-header">

              <h3 class="card-title">Expense  Create</h3>
            </div>

            <form action="{{route('admin.store.expense')}}" method="POST" enctype="multipart/form-data">
              @csrf
              <input type="hidden" name="group_id" value="{{$group_id}}">
              <div class="card-body">
              <div class="form-group">
                  <label for="exampleInputEmail1">Title</label>
                  <input type="text" name="title" class="form-control" id="title" value="{{ old('title') }}" placeholder="Enter Title">
                  {!! $errors->first('title', '<p style="color:red;" class="help-block error">:message</p>') !!}
                </div>
                <div class="form-group">
                  <label for="exampleInputEmail1">Description</label>
                  <input type="text" name="description" class="form-control" id="description" value="{{ old('description') }}" placeholder="Enter Desc">
                  {!! $errors->first('description', '<p style="color:red;" class="help-block error">:message</p>') !!}
                </div>
                <div class="form-group">
                  <label for="exampleInputEmail1">Total Amount</label>
                  <input type="number" name="total_amount" class="form-control" id="total_amount" value="{{ old('total_amount') }}" placeholder="Enter Amount">
                  {!! $errors->first('total_amount', '<p style="color:red;" class="help-block error">:message</p>') !!}
                </div>
                <div class="form-group">
                  <label for="exampleInputEmail1">Paying Users</label>
                  <select class="selectpicker" name="users[]" multiple data-live-search="true">
                    @foreach($users as $user)
                    <option value="{{$user->id}}">{{$user->name}}</option>
                    @endforeach
                  </select>
                </div>
              </div>
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
        </div>

      </div>


  </section>
</div>
<script>
  $('select').selectpicker();

</script>
@endsection

resources/views/admin/groups/edit.blade.php
@extends('admin.layouts.master')

@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Group
      <small>Manage</small>
    </h1>

    @if ($message = Session::get('message'))
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <h5><i class="icon fa fa-check"></i> {!! $message !!}</h5>

    </div>
    @endif
  </section>

  <section class="content">
    <div class="container-fluid">
      <div class="row">

        <div class="col-md-12">
          <div class="card card-primary">
            <div class="card-header">

              <h3 class="card-title">Edit Group</h3>
            </div>

            <form action="{{route('admin.group.update')}}" method="POST" enctype="multipart/form-data">
              @csrf
              <input type="hidden" name="group_id" value="{{encrypt($group->id)}}">
              <div class="card-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">Title</label>
                  <input type="tezt" name="title" class="form-control" id="title" value="{{ old('title', isset($group) ? $group->title : '') }}" placeholder="Enter Title">
                  {!! $errors->first('title', '<p style="color:red;" class="help-block error">:message</p>') !!}
                </div>
                <div class="form-group">
                  <label for="exampleInputEmail1">Description</label>
                  <input type="tezt" name="description" class="form-control" id="description" value="{{ old('description', isset($group) ? $group->description : '') }}" placeholder="Enter Desc">
                  {!! $errors->first('description', '<p style="color:red;" class="help-block error">:message</p>') !!}
                </div>
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
        </div>

      </div>


  </section>
</div>

@endsection

resources/views/admin/groups/index.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            Group
            <small>Manage</small>
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="panel panel-default">
                    <div class="panel-heading"></div>
                    <div class="panel-body">

                        <div class="col-md-12">
                            <form method="GET" action="" accept-charset="UTF-8" class="navbar-form " role="search">
                                <div class="row">
                                    <div class="form-group ">
                                        <div class="col-md-12">
                                            <input type="text" class="form-control" value="{{Request::get('search')}}" name="search" placeholder="Search key">
                                        </div>
                                    </div>
                                    <div class="form-group ">
                                        <button class="btn btn-primary" type="submit">
                                            <i class="fa fa-search"></i>
                                        </button>
                                        <a href="" class="btn  btn-warning">Clear</a>

                                    </div>
                                </div>
                            </form>
                        </div>
                        <br />
                        <br />
                        <div class="col-md-12">
                            <a href="{{route('admin.group.create')}}" class="btn btn-success btn-sm" title="Add New ">
                                <i class="fa fa-plus" aria-hidden="true"></i> Add New
                            </a>
                        </div>
                        <div class="table-responsive col-md-12">
                            <br />
                            <br />
                            <table class="table table-borderless">
                                <tr>
                                    <th>Id</th>
                                    <th style="width: 30%;">Title</th>
                                    <th>Action</th>
                                </tr>
                                @if(isset($groups))

                                @foreach($groups as $group)

                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $group->title }}</td>


                                    </td>
                                    <td>
                                        <a href="{{route('admin.group.edit',[encrypt($group->id)])}}" title="Edit Group" class="btn btn-primary">
                                            Edit
                                        </a>
                                        <form method="POST" action="{{route('admin.group.delete')}}" accept-charset="UTF-8" style="display:inline">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="id" value="{{encrypt($group->id)}}">
                                            <button type="submit" class="btn btn-danger" title="Delete Group" onclick="return confirm('Are you sure?')">
                                                Delete
                                            </button>
                                        </form>
                                        <a href="{{route('admin.group.add.user',[encrypt($group->id)])}}" title="add user" class="btn btn-success">
                                            <i class='fas fa-user-alt' style='font-size:24px'></i>
                                        </a>
                                        <a href="{{route('admin.group.expense.create',[encrypt($group->id)])}}" title="add expense" class="btn btn-primary">Expense</a>
                                        <a href="{{route('admin.group.expense.view',[encrypt($group->id)])}}" title="view expense" class="btn btn-primary"><i class="fa fa-eye" aria-hidden="true"></i></a>
                                    </td>
                                </tr>
                                @endforeach
                                @else
                                <tr>
                                    <td colspan="4">No records found</td>
                                </tr>
                                @endif


                            </table>



                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script>
            function check() {

                var r = confirm("Are you sure wanted to delete?");

                if (r) {
                    return true;
                } else {
                    return false;
                }
            }
        </script>
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

@endsection

resources/views/admin/groups/view_expense.blade.php
@extends('admin.layouts.master')

@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Expense
      <small>Manage</small>
    </h1>

    @if ($message = Session::get('message'))
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <h5><i class="icon fa fa-check"></i> {!! $message !!}</h5>

    </div>
    @endif
  </section>

  <section class="content">
    <div class="container-fluid">
      <div class="row">

        <div class="col-md-12">
          <div class="card card-primary">
            <div class="card-header">

              <h3 class="card-title">View Expense</h3>
            </div>

            <div>
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Date</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($expenses as $expense)
                  <tr>
                    <th scope="row">{{$loop->iteration}}</th>
                    <td>{{$expense->title}}</td>
                    <td>{{$expense->total_amount}}</td>
                    <td>{{date('d-m-Y', strtotime($expense->created_at))}}</td>
                    <td>
                    <a href="{{route('admin.expense.detail',[encrypt($expense->id)])}}" title="View Bill" class="btn btn-primary">  <i class="fa fa-eye" aria-hidden="true"></i></a>

                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>

      </div>


  </section>
</div>
@endsection

resources/views/admin/groups/view_expense_detail.blade.php
@extends('admin.layouts.master')

@section('content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Expense
      <small>Manage</small>
    </h1>

    @if ($message = Session::get('message'))
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <h5><i class="icon fa fa-check"></i> {!! $message !!}</h5>

    </div>
    @endif
  </section>

  <section class="content">
    <div class="container-fluid">
      <div class="row">

        <div class="col-md-12">
          <div class="card card-primary">
            <div class="card-header">

              <h3 class="card-title">Total Expanse - INR.{{$expenses->sum('amount')}}</h3>
            </div>

            <div id="print-list">
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Date</th>
                    <th  scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($expenses as $expense)
                  <tr>
                    <th scope="row">{{$loop->iteration}}</th>
                    <td>{{$expense->user->name}}</td>
                    <td>{{$expense->amount }}</td>
                    <td>{{date('d-m-Y', strtotime($expense->created_at))}}</td>
                    <td>
                    <a href="#" id="printPageButton" onclick="printBill('print-list')" title="View Bill" class="btn btn-primary">  <i class="fa fa-print" aria-hidden="true"></i></a>

                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>

      </div>


  </section>
</div>
<script>
   function printBill(divID) {
        //Get the HTML of div
        var divElements = document.getElementById(divID).innerHTML;
        //Get the HTML of whole page
        var oldPage = document.body.innerHTML;
        //Reset the page's HTML with div's HTML only
        document.body.innerHTML = 
          "<html><head><title></title></head><body>" + 
          divElements + "</body>";
        //Print Page
        window.print();
        //Restore orignal HTML
        document.body.innerHTML = oldPage;

    }
</script>
@endsection