routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::group(['namespace'=>'Frontend'],function(){

//     Route::get('/', [   'uses' => 'HomeController@index'])->name('index');
//     Route::get('/media', ['uses' => 'HomeController@media'])->name('media');
//     Route::get('/contact', ['uses' => 'HomeController@contact'])->name('contact');
//     Route::get('/faq', ['uses' => 'HomeController@faq'])->name('faq');
//     Route::get('/gallery', ['uses' => 'HomeController@gallery'])->name('gallery');
//     Route::get('/awards', ['uses' => 'HomeController@awards'])->name('awards');
//     Route::get('/case-studies', ['uses' => 'HomeController@caseStudies'])->name('casestudies');
//     Route::get('/case-study/{slug}', ['uses' => 'HomeController@caseStudydetails'])->name('casestudy.details');
// });

Route::get('/manage', ['uses' => 'Admin\AdminController@login'])->name('admin.login.form');
Route::post('login', ['uses' => 'Admin\AdminController@adminLogin'])->name('admin.login');

Route::group(['prefix' => 'admin-manage', 'namespace' => 'Admin','as'=>'admin.', 'middleware' => 'isAdmin'], function () {

    Route::post('logout', ['uses' => 'AdminController@logout'])->name('logout');
    Route::get('dashboard', ['uses' => 'AdminController@dashboard'])->name('dashboard');

    Route::get('user-list', ['uses' => 'UserController@index'])->name('users');
    Route::get('user-create', ['uses' => 'UserController@create'])->name('user.create');
    Route::post('store-user', ['uses' => 'UserController@store'])->name('user.save');
    Route::get('edit-user/{id}', ['uses' => 'UserController@edit'])->name('user.edit');
    Route::post('update-user', ['uses' => 'UserController@update'])->name('user.update');
    Route::post('delete-user', ['uses' => 'UserController@delete'])->name('user.delete');

    Route::get('group-list', ['uses' => 'GroupController@index'])->name('groups');
    Route::get('group-create', ['uses' => 'GroupController@create'])->name('group.create');
    Route::post('store-groups', ['uses' => 'GroupController@store'])->name('group.save');
    Route::get('edit-groups/{id}', ['uses' => 'GroupController@edit'])->name('group.edit');
    Route::post('update-groups', ['uses' => 'GroupController@update'])->name('group.update');
    Route::post('delete-groups', ['uses' => 'GroupController@delete'])->name('group.delete');

    Route::get('add-user-to-groups/{id}', ['uses' => 'GroupController@addUsers'])->name('group.add.user');
    Route::post('add-user-to-group', ['uses' => 'GroupController@addUsersToGroup'])->name('group.add-user');
    Route::get('create-expense/{id}', ['uses' => 'GroupController@createExpense'])->name('group.expense.create');
    Route::post('store-expense', ['uses' => 'GroupController@storeExpense'])->name('store.expense');
    Route::get('view-expense/{id}', ['uses' => 'GroupController@viewExpense'])->name('group.expense.view');
    Route::get('view-bill/{id}', ['uses' => 'GroupController@viewExpenseDetails'])->name('expense.detail');


});

resources/views/admin/layouts/footer.blade.php
<footer class="footer pt-0">
    <div class="row align-items-center justify-content-lg-between">
        <div class="col-lg-6">
            <div class="copyright text-center  text-lg-left  text-muted">
                &copy; 2020 <a href="#" class="font-weight-bold ml-1" target="_blank"></a>
            </div>
        </div>
        <div class="col-lg-6">
            <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                <li class="nav-item">
                <a href="#" class="nav-link" target="_blank">About Us</a>
                </li>
                <li class="nav-item">
                <a href="#" class="nav-link" target="_blank">Blog</a>
                </li>
            </ul>
        </div>
    </div>
</footer>

resources/views/admin/layouts/header.blade.php
<!-- Header -->
<div class="header pb-6 d-flex align-items-center logn-hdr" style="min-height: 155px;">


<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light" id="sidenav-main">
  <div class="scrollbar-inner">
    <!-- Brand -->
    <div class="sidenav-header  align-items-center">
      <a class="navbar-brand lgn-brand" href="javascript:void(0)">
        <img src="{{asset('public/admin/assets/img/brand/blue.png')}}" class="navbar-brand-img" alt="...">
      </a>
    </div>
  </div>
</nav>
<!-- Mask -->
<span class="mask bg-gradient-default"></span>
<!-- Header container -->

</div>

resources/views/admin/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Dashboard</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <link rel="stylesheet" href="{{asset('public/admin/plugins/fontawesome-free/css/all.min.css')}}">
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="stylesheet" href="{{asset('public/admin/dist/css/adminlte.min.css')}}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
<style>
  @media print {
  #printPageButton {
    display: none;
  }
}
</style>
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{{route('admin.dashboard')}}" class="nav-link">Home</a>
      </li>

    </ul>
    <ul class="navbar-nav ml-auto">
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">


                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <img src="{{asset('public/web/images/prich.png')}}" class="user-image" alt="User Image">
                        <span class="hidden-xs">Rahim</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="{{asset('public/web/images/prich.png')}}" class="img-circle" alt="User Image">

                            <p>Administrator
                                <small>Admin</small>
                            </p>
                        </li>
                        <li class="user-footer">
                            {{-- <div class="pull-left">
                                <a href="" class="btn btn-default btn-flat">Profile</a>
                            </div> --}}
                            <div class="pull-right">
                                <a class="btn btn-default btn-flat" href="{{route('admin.logout')}}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fa fa-power-off"></i> Logout</a>
                                <form id="logout-form" action="{{route('admin.logout')}}" method="POST" style="display: none;">
                                    @csrf                              </form>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>

  </nav>
@include('admin.layouts.sidebar')
  @yield('content')
  <aside class="control-sidebar control-sidebar-dark">
  </aside>
  <footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">Test</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.1.0-rc
    </div>
  </footer>
</div>
<!-- <script src="{{asset('public/admin/plugins/jquery/jquery.min.js')}}"></script> -->
<!-- <script src="{{asset('public/admin/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script> -->
<script src="{{asset('public/admin/dist/js/adminlte.js')}}"></script>
<script src="{{asset('public/admin/dist/js/demo.js')}}"></script>
<script src="{{asset('public/admin/dist/js/pages/dashboard3.js')}}"></script>
</body>
</html>

resources/views/admin/layouts/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{route('admin.dashboard')}}" class="brand-link">
      <img src="{{asset('public/admin/dist/img/AdminLTELogo.png')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Split Wise</span>
    </a>
    <div class="sidebar">
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{asset('public/admin/dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
        </div>
      </div>
        <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
              {{-- <li class="nav-item">
            <a href="#" class="nav-link ">
              <i class="fa fa-users"></i>
              <p>
                Accounts
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>

          </li> --}}


          <li class="nav-item">
            <a href="#" class="nav-link ">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                CMS
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{route('admin.users')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Users</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{route('admin.groups')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Groups</p>
                </a>
              </li>
            </ul>
          </li>



        </ul>
        </nav>
    </div>
  </aside>