routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::group(['namespace'=>'Frontend'],function(){

//     Route::get('/', [   'uses' => 'HomeController@index'])->name('index');
//     Route::get('/media', ['uses' => 'HomeController@media'])->name('media');
//     Route::get('/contact', ['uses' => 'HomeController@contact'])->name('contact');
//     Route::get('/faq', ['uses' => 'HomeController@faq'])->name('faq');
//     Route::get('/gallery', ['uses' => 'HomeController@gallery'])->name('gallery');
//     Route::get('/awards', ['uses' => 'HomeController@awards'])->name('awards');
//     Route::get('/case-studies', ['uses' => 'HomeController@caseStudies'])->name('casestudies');
//     Route::get('/case-study/{slug}', ['uses' => 'HomeController@caseStudydetails'])->name('casestudy.details');
// });

Route::get('/manage', ['uses' => 'Admin\AdminController@login'])->name('admin.login.form');
Route::post('login', ['uses' => 'Admin\AdminController@adminLogin'])->name('admin.login');

Route::group(['prefix' => 'admin-manage', 'namespace' => 'Admin','as'=>'admin.', 'middleware' => 'isAdmin'], function () {

    Route::post('logout', ['uses' => 'AdminController@logout'])->name('logout');
    Route::get('dashboard', ['uses' => 'AdminController@dashboard'])->name('dashboard');

    Route::get('user-list', ['uses' => 'UserController@index'])->name('users');
    Route::get('user-create', ['uses' => 'UserController@create'])->name('user.create');
    Route::post('store-user', ['uses' => 'UserController@store'])->name('user.save');
    Route::get('edit-user/{id}', ['uses' => 'UserController@edit'])->name('user.edit');
    Route::post('update-user', ['uses' => 'UserController@update'])->name('user.update');
    Route::post('delete-user', ['uses' => 'UserController@delete'])->name('user.delete');

    Route::get('group-list', ['uses' => 'GroupController@index'])->name('groups');
    Route::get('group-create', ['uses' => 'GroupController@create'])->name('group.create');
    Route::post('store-groups', ['uses' => 'GroupController@store'])->name('group.save');
    Route::get('edit-groups/{id}', ['uses' => 'GroupController@edit'])->name('group.edit');
    Route::post('update-groups', ['uses' => 'GroupController@update'])->name('group.update');
    Route::post('delete-groups', ['uses' => 'GroupController@delete'])->name('group.delete');

    Route::get('add-user-to-groups/{id}', ['uses' => 'GroupController@addUsers'])->name('group.add.user');
    Route::post('add-user-to-group', ['uses' => 'GroupController@addUsersToGroup'])->name('group.add-user');
    Route::get('create-expense/{id}', ['uses' => 'GroupController@createExpense'])->name('group.expense.create');
    Route::post('store-expense', ['uses' => 'GroupController@storeExpense'])->name('store.expense');
    Route::get('view-expense/{id}', ['uses' => 'GroupController@viewExpense'])->name('group.expense.view');
    Route::get('view-bill/{id}', ['uses' => 'GroupController@viewExpenseDetails'])->name('expense.detail');


});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use  HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'mobile',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
   /*  public function group(){
        return $this->belongsToMany('App\Models\Group');

    } */
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Validator;

class UserController
{
    /**
     * Show a list of all of the application's users.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $users = User::latest()->get();
        return view('admin.users.index', compact('users'));
    }
    /**
     * Create the user
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {

        return view('admin.users.create');
    }
    /**
     * Edit the given User.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  string  $id
     * @return \Illuminate\View\View
     */
    public function edit($id)
    {
        $user = User::find(decrypt($id));
        return view('admin.users.edit', compact('user'));
    }
    /**
     * Store the user.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $validator = Validator::make(request()->all(), [
            'name' => 'required', 'email' => 'required|email'
        ], ['name.required' => 'Please Fill Title']);
        if ($validator->passes()) {
            $input = request()->except('_token');
            User::create($input);
            return back()->with('message', 'Successfully Created New User');
        } else {
            return back()->withErrors($validator)->withInput(request()->all());
        }
    }
    /**
     * Update the user.
     * @param  string  $id
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {

        $id = decrypt($request->user_id);
        $validator = Validator::make(request()->all(), [
            'name' => 'required', 'email' => 'required|email'
        ], ['name.required' => 'Please Fill Title']);
        if ($validator->passes()) {
            $input = request()->except('_token', 'image');
            User::find($id)->update($input);
            return back()->with('message', 'Successfully Updated User');
        } else {

            return back()->withErrors($validator)->withInput(request()->all());
        }
    }
    /**
     * Destroy the user data.
     * @param  string  $id
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function delete(Request $request)
    {
        $id = $request->id;
        $data = User::find(decrypt($id));
        $data->delete();
        return redirect(route('admin.users'))->with('success', 'Successfully Deleted User');
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.master')

@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Users
      <small>Manage</small>
    </h1>

    @if ($message = Session::get('message'))
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <h5><i class="icon fa fa-check"></i> {!! $message !!}</h5>

    </div>
    @endif
  </section>

  <section class="content">
    <div class="container-fluid">
      <div class="row">

        <div class="col-md-12">
          <div class="card card-primary">
            <div class="card-header">

              <h3 class="card-title">Create User</h3>
            </div>

            <form action="{{route('admin.user.save')}}" method="POST" enctype="multipart/form-data">
              @csrf
              <div class="card-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">Name</label>
                  <input type="tezt" name="name" class="form-control" id="name" value="{{ old('name') }}" placeholder="Enter Name">
                  {!! $errors->first('name', '<p style="color:red;" class="help-block error">:message</p>') !!}
                </div>
                <div class="form-group">
                  <label for="exampleInputEmail1">Email</label>
                  <input type="tezt" name="email" class="form-control" id="email" value="{{ old('email') }}" placeholder="Enter Email">
                  {!! $errors->first('email', '<p style="color:red;" class="help-block error">:message</p>') !!}
                </div>
                <div class="form-group">
                  <label for="exampleInputEmail1">Mobile</label>
                  <input type="tezt" name="mobile" class="form-control" id="mobile" value="{{ old('mobile') }}" placeholder="Enter Mobile">
                  {!! $errors->first('mobile', '<p style="color:red;" class="help-block error">:message</p>') !!}
                </div>
              </div>
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
        </div>

      </div>


  </section>
</div>

@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.master')

@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      User
      <small>Manage</small>
    </h1>

    @if ($message = Session::get('message'))
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <h5><i class="icon fa fa-check"></i> {!! $message !!}</h5>

    </div>
    @endif
  </section>

  <section class="content">
    <div class="container-fluid">
      <div class="row">

        <div class="col-md-12">
          <div class="card card-primary">
            <div class="card-header">

              <h3 class="card-title">Edit User</h3>
            </div>

            <form action="{{route('admin.user.update')}}" method="POST" enctype="multipart/form-data">
              @csrf
              <input type="hidden" name="user_id" value="{{encrypt($user->id)}}">
              <div class="card-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">Name</label>
                  <input type="tezt" name="name" class="form-control" id="name" value="{{ old('name', isset($user) ? $user->name : '') }}" placeholder="Enter Title">
                  {!! $errors->first('name', '<p style="color:red;" class="help-block error">:message</p>') !!}
                </div>
                <div class="form-group">
                  <label for="exampleInputEmail1">Email</label>
                  <input type="tezt" name="email" class="form-control" id="email" value="{{ old('email', isset($user) ? $user->email : '') }}" placeholder="Enter Title">
                  {!! $errors->first('email', '<p style="color:red;" class="help-block error">:message</p>') !!}
                </div>
                <div class="form-group">
                  <label for="exampleInputEmail1">Mobile</label>
                  <input type="tezt" name="mobile" class="form-control" id="mobile" value="{{ old('mobile', isset($user) ? $user->mobile : '') }}" placeholder="Enter Title">
                  {!! $errors->first('mobile', '<p style="color:red;" class="help-block error">:message</p>') !!}
                </div>
               
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
        </div>

      </div>


  </section>
</div>

@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                User
                <small>Manage</small>
            </h1>
        </section>

        <section class="content">
            <div class="row">
                <div class="col-md-12">

                    <div class="panel panel-default">
                        <div class="panel-heading"></div>
                        <div class="panel-body">

                            <div class="col-md-12">
                                <form method="GET" action=""
                                      accept-charset="UTF-8" class="navbar-form " role="search">
                                    <div class="row">
                                        <div class="form-group ">
                                            <div class="col-md-12">
                                                <input type="text" class="form-control" value="{{Request::get('search')}}" name="search"
                                                       placeholder="Search key">
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <button class="btn btn-primary" type="submit">
                                                <i class="fa fa-search"></i>
                                            </button>
                                            <a href=""     class="btn  btn-warning">Clear</a>

                                        </div>
                                    </div>
                                </form>
                            </div>
                            <br/>
                            <br/>
                            <div class="col-md-12">
                                <a href="{{route('admin.user.create')}}"
                                   class="btn btn-success btn-sm" title="Add New ">
                                    <i class="fa fa-plus" aria-hidden="true"></i> Add New
                                </a>
                            </div>
                            <div class="table-responsive col-md-12">
                                <br/>
                                <br/>
                                <table class="table table-borderless">
                                    <tr>
                                        <th>Id</th>
                                        <th style="width: 30%;">Name</th>
                                        <th>Email</th>
                                        <th>Action</th>
                                    </tr>
                                    @if(isset($users))

                                        @foreach($users as $user)

                                            <tr>
                                                <td>{{ $loop->iteration }}</td>
                                                <td>{{ $user->name }}</td>
                                                <td>{{ $user->email }}</td>


                                                </td>
                                                <td>
                                                   <a  href="{{route('admin.user.edit',[encrypt($user->id)])}}" class="btn btn-primary">
                                                   Edit
                                                    </a>

                                                    <form method="POST" action="{{route('admin.user.delete')}}" accept-charset="UTF-8" style="display:inline">
                                                        {{ csrf_field() }}
                                                        <input type="hidden" name="id" value="{{encrypt($user->id)}}">
                                                        <button type="submit" class="btn btn-danger" title="Delete Product" onclick="return confirm('Are you sure?')">
                                                              Delete
                                                        </button>
                                                    </form>
                                                    <br/>
                                                    <br/>
                                                </td>
                                            </tr>
                                        @endforeach
                                    @else
                                        <tr>
                                            <td colspan="4">No records found</td>
                                        </tr>
                                    @endif


                                </table>



                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <script>
                function check() {

                    var r = confirm("Are you sure wanted to delete?");

                    if (r) {
                        return true;
                    } else {
                        return false;
                    }
                }
            </script>
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

@endsection